services:
  - type: web
    name: saude-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://es2-gerenciador-de-clinica.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
